### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by matasoy** [dumbmatter/screw#1]
Try it here is not working sample, can u make it work please?

**Comment by dumbmatter** [comment]
Works for me. Can you be more specific about what "not working" means?

**Comment by matasoy** [comment]
ı select the mp3 file. Then nothing happened. Looking the console and "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page" this warning there.  After select file, we should press plat to start. Chrome dont allow to play automaticly.

**Comment by dumbmatter** [comment]
Yep you're right, seems to be broken in Chrome. I was using Firefox which still works.

**Comment by matasoy** [comment]
Add a start button instead of autostart

25 Mar 2022 Cum 22:47 tarihinde Jeremy Scheff ***@***.***>
şunu yazdı:

**Comment by dumbmatter** [comment]
Not needed, selecting the MP3 counts as a user interaction :)

It's fixed now, thanks for letting me know it was broken!
